### ISSUE TITLE
Never sending `textDocument/completion`

### ISSUE THREAD

**Issue by yaroslavyaroslav** [sublimelsp/LSP-marksman#24]
1. Install plugin
2. Add `.marksman.toml` into folder with markdown documents
3. Start type a wikilink link `[[F|]]`

Not just no completion with a path appearing, no `textDocument/completion` request sent to server as well. It got sending `textDocument/codeLens` and `textDocument/codeAction` requests after `textDocument/didChange`.

Is it me or is it expected behaviour?

**Comment by jfcherng** [comment]
It sends if I trigger autocompletion manually.

**Comment by yaroslavyaroslav** [comment]
Yeah, after some hustling it fixed for me too.
