### ISSUE TITLE
Server doesn't initialize

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP-marksman#4]
I wanted to try out this server for fun, but it doesn't seem to work on Windows.

The executable gets correctly installed into `Package Storage\LSP-marksman\bin\marksman.exe`.
No errors in the console, it just never initializes.

![Unbenannt](https://user-images.githubusercontent.com/6579999/188156804-c804dbfd-35eb-41a0-88b2-4b2851cda6a1.png)

**Comment by jfcherng** [comment]
It looks like it's very important that the markdown file must be in a project when its first time open.

**Comment by jwortmann** [comment]
Indeed that seems to be the cause. I guess it is a server bug then. Or can we somehow prevent to start the server if there are no workspace folders?

It's a bit surprising that the server requires a workspace forlder, I would expect servers for Markdown files to work in single-file mode.

**Comment by jwortmann** [comment]
I opened https://github.com/artempyanykh/marksman/issues/66
