### ISSUE TITLE
Configuring (e.g., Table of Contents)

### ISSUE THREAD

**Issue by reagle** [sublimelsp/LSP-marksman#6]
How do I disable the ToC suggestion? Also, is there a way to configure what warnings show in the linting?

**Comment by jfcherng** [comment]
> Also, is there a way to configure what warnings show in the linting?

I don't see any and I think there won't be any.
https://github.com/artempyanykh/marksman/issues/84

**Comment by jwortmann** [comment]
For the "Create Table of Contents" code action, you could comment in https://github.com/sublimelsp/LSP/issues/1846 on how you would expect the different kinds of code actions to be presented in the editor. There are three different code action kinds "quickfix", "refactor" and "source" currently defined in the [LSP specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionKind), and this ToC action has the "source" kind.

Having more opinions would increase the chance of moving forward with improvements.

From the side of the LSP package, there is currently no way to disable only a particular code action - the only thing possible would be `"show_code_actions": ""` to disable all code actions for all servers.

**Comment by reagle** [comment]
I don't know much about LSP (or code actions), I just know that if I need a ToC, I'll have pandoc generate it so it was annoying to have the suggestion *always* show on the right side of the line I was editing. Again, I don't know anything about LSP or the underlying architecture, only that it'd be nice to turn an action off somehow.

**Comment by rchl** [comment]
See this marksman issue I've just created: https://github.com/artempyanykh/marksman/issues/90
We'll see what comes out of it.

**Comment by artempyanykh** [comment]
My 2¢: the easiest would likely be adding a Marksman config to disable the TOC code action (can be a part of https://github.com/artempyanykh/marksman/issues/91).

**Comment by rchl** [comment]
I'm thinking that on our (ST LSP) side we will start filtering out `source` actions so this problem will be fixed anyway. It's not an issue that the code action exists, it's only an issue that it appears in the view for every line in the file.

Given how we will behave and how VSCode behaves, I don't think it will really be necessary to add configuration for it.

**Comment by rchl** [comment]
Sublime LSP from 1.20.0 is filtering out source code action for implicit code action requests.
