### ISSUE TITLE
Wikilinks are not triggered

### ISSUE THREAD

**Issue by gour** [sublimelsp/LSP-marksman#8]
Hello,

I'm trying to use this package with ST4, but it does not recognize `[[Wikilinks]]`. I was told in `#lsp` that it probably a marksman issue, so I've opened a ticket https://github.com/artempyanykh/marksman/issues/112.

However, today I build Helix editor from the source and tried with it and everything does work as expected as you see see from the shot below:

![marksman-hx](https://user-images.githubusercontent.com/114592/202850490-f7e664d2-c830-4783-ba23-0a5eb05be45f.png)

Here are my simple two notes to test:

[first.md](https://github.com/sublimelsp/LSP-marksman/files/10046955/first.md)
[second.md](https://github.com/sublimelsp/LSP-marksman/files/10046956/second.md)

Any idea?

**Comment by jfcherng** [comment]
Not working in VSCode either. So I think there must be some other setup to make it work.
![image](https://user-images.githubusercontent.com/6594915/202852126-bb4191a3-503e-4c6c-a3fa-8ae26fb6d0d3.png)

**Comment by jfcherng** [comment]
So I think `marksman` doesn't recognize this somehow...

```md
---
title: "Second Note"
tags: ["test"]
---
```

Since traditional `h1` header works fine.

![image](https://user-images.githubusercontent.com/6594915/202852574-cd1253e3-dccd-4487-bc5f-0fb9d29478cf.png)

**Comment by gour** [comment]
> So I think `marksman` doesn't recognize this style...
> 
> ```lisp
> ---
> title: "Second Note"
> tags: ["test"]
> ---
> ```
> 
> because traditional `h1` header works fine.
> 
> ![image](https://user-images.githubusercontent.com/6594915/202852574-cd1253e3-dccd-4487-bc5f-0fb9d29478cf.png)

Yes, after adding 1st-leveal headers to my note, auto-completion has improved...

**Comment by predragnikolic** [comment]
Closing this as there is nothing that this repo can do.

The feature request is opened [here](https://github.com/artempyanykh/marksman/issues/112), feel free to subscribe there
